@startuml

title __MANAGER's Class Diagram__\n

  package Akali {
    package Akali.manager {
      class AddController {
          - cancel : Button
          - browseText : Button
          - browseAudio : Button
          - save : Button
          - text : TextField
          - title : TextField
          - language : TextField
          - discoverer : TextField
          - pages : TextField
          - words : TextField
          - audio : TextField
          - region : ChoiceBox
          - status : ChoiceBox
          - type : ChoiceBox
          ~ handleCancel()
          ~ handleSave()
          ~ displaybrowse()
          ~ changeBrowseTextField()
      }
    }
  }
  

  package Akali {
    package Akali.manager {
      class ManageController {
          - text : TextField
          - title : TextField
          - lang : TextField
          - pages : TextField
          - words : TextField
          - discoverer : TextField
          - audio : TextField
          - audioBrowse : Button
          - textBrowse : Button
          - save : Button
          - delete : Button
          - cancel : Button
          - region : ComboBox
          - status : ComboBox
          - type : ComboBox
          - wintitle : Label
          ~ handleCancel()
          ~ handleSave()
          ~ displayBrowse()
          ~ handleDelete()
          ~ changeBrowseTextField()
      }
    }
  }
  

  package Akali {
    package Akali.manager {
      class ManageResourceController {
          - back : Button
          - download : Button
          - rejectj : Button
          - approve : Button
          - comment : TextArea
          - lang : Label
          - stat : Label
          - type : Label
          - title : Label
          ~ handleBack()
          ~ handleDownload()
          ~ handleReject()
          ~ handleApprove()
          ~ initialize()
      }
    }
  }
  

  package Akali {
    package Akali.manager {
      class ManagerPendingController {
          - back : Button
          - table : TableView
          - title : TableColumn
          - status : TableColumn
          - buttonact : TableColumn
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
